Repository harrytmthy/safebox, pull requests merged in 2025-06, with the labels that each got.

#14 feat(state): Add SafeBoxGlobalStateObserver and closeWhenIdle support
  safebox/src/androidTest/java/com/harrytmthy/safebox/storage/SafeBoxBlobStoreTest.kt
  safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
  safebox/src/main/java/com/harrytmthy/safebox/registry/SafeBoxBlobFileRegistry.kt
  safebox/src/main/java/com/harrytmthy/safebox/state/SafeBoxGlobalStateObserver.kt
  safebox/src/main/java/com/harrytmthy/safebox/state/SafeBoxState.kt
  safebox/src/main/java/com/harrytmthy/safebox/storage/SafeBoxBlobStore.kt
  safebox/src/test/java/com/harrytmthy/safebox/state/SafeBoxGlobalStateObserverTest.kt
Labels: enhancement

#16 fix(pipeline): Verify GPG and secret injection in publish workflow
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: ci, fix

#21 release: v1.1.0-beta01 with SafeBoxStateManager and improved lifecycle coordination
  CHANGELOG.md
  safebox/build.gradle.kts
Labels: release

#24 feat(keystore): Add XOR based masking to SafeSecretKey for in-memory protection
  safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
  safebox/src/main/java/com/harrytmthy/safebox/cryptography/ChaCha20CipherProvider.kt
  safebox/src/main/java/com/harrytmthy/safebox/cryptography/CipherProvider.kt
  safebox/src/main/java/com/harrytmthy/safebox/keystore/KeyProvider.kt
  safebox/src/main/java/com/harrytmthy/safebox/keystore/SafeSecretKey.kt
  safebox/src/main/java/com/harrytmthy/safebox/keystore/SecureRandomKeyProvider.kt
Labels: enhancement

#27 refactor(keystore): Enable concurrent access for SafeSecretKey and SecureRandomKeyProvider
  safebox/src/main/java/com/harrytmthy/safebox/keystore/SafeSecretKey.kt
  safebox/src/main/java/com/harrytmthy/safebox/keystore/SecureRandomKeyProvider.kt
Labels: enhancement

#29 refactor(crypto): Make Cipher instance initialized on-demand inside AesGcmCipherProvider
  safebox/src/androidTest/java/com/harrytmthy/safebox/cryptography/AesCtrCipherProviderTest.kt
  safebox/src/main/java/com/harrytmthy/safebox/cryptography/AesCtrCipherProvider.kt
  safebox/src/main/java/com/harrytmthy/safebox/cryptography/AesGcmCipherProvider.kt
Labels: enhancement, security

#30 feat(crypto): Add CipherPool with SafeBoxExecutor to handle cryptographic concurrency
  safebox/src/main/java/com/harrytmthy/safebox/concurrent/SafeBoxExecutor.kt
  safebox/src/main/java/com/harrytmthy/safebox/cryptography/ChaCha20CipherProvider.kt
  safebox/src/main/java/com/harrytmthy/safebox/cryptography/CipherPool.kt
  safebox/src/main/java/com/harrytmthy/safebox/cryptography/SingletonCipherPoolProvider.kt
  safebox/src/test/java/com/harrytmthy/safebox/cryptography/CipherPoolTest.kt
Labels: enhancement, security

#31 refactor(crypto): Change BouncyCastleProvider init behavior
  safebox/src/main/java/com/harrytmthy/safebox/cryptography/ChaCha20CipherProvider.kt
  safebox/src/main/java/com/harrytmthy/safebox/cryptography/CipherPool.kt
  safebox/src/main/java/com/harrytmthy/safebox/cryptography/SingletonCipherPoolProvider.kt
Labels: refactor

#33 release: v1.1.0-rc01 with improved security and concurrency
  CHANGELOG.md
  README.md
  safebox/build.gradle.kts
Labels: release

#36 docs: Add the v1.1.0 benchmark results to README
  README.md
  docs/charts/v1_1_get_performance_chart.png
  docs/charts/v1_1_put_and_commit_performance_chart.png
  docs/charts/v1_1_put_performance_chart.png
Labels: documentation

#38 chore: Enable GitHub Sponsors button
  .github/FUNDING.yml
  README.md
Labels: documentation, chore

#40 docs: Add Build, License, and Version badges
  README.md
Labels: documentation

#41 release: v1.1.0 with improved state management, security, and concurrency
  CHANGELOG.md
  README.md
  safebox/build.gradle.kts
Labels: release

#46 refactor: Deprecate harrytmthy-dev namespace
  .github/CODEOWNERS
  .github/FUNDING.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/MIGRATION.md
  gradle/libs.versions.toml
  safebox/build.gradle.kts
Labels: refactor

#48 feat(pipeline): Enable Gradle caching to improve CI performance
  .github/workflows/ci.yml
Labels: enhancement, ci
